# Generated by Django 5.0.1 on 2024-01-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordleProgress',
            fields=[
                ('ip_address', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('ongoing', models.BooleanField(default=True)),
                ('data', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
