# Generated by Django 5.0.1 on 2024-01-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_wordleprogress_curr_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordleprogress',
            name='ongoing',
        ),
        migrations.AddField(
            model_name='wordleprogress',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
