# Generated by Django 5.0.1 on 2024-07-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_wordleprogress_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlist',
            name='word',
            field=models.CharField(max_length=6),
        ),
    ]
