# Generated by Django 5.0.1 on 2024-07-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_wordlist_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordleStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempted', models.IntegerField(default=0)),
                ('total_solved', models.IntegerField(default=0)),
            ],
        ),
    ]
