# Generated by Django 5.0.1 on 2024-10-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_wordlestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, unique=True)),
                ('category', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('winner', models.IntegerField(default=0)),
            ],
        ),
    ]
