# Generated by Django 5.0.1 on 2025-02-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_essays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essays',
            old_name='author',
            new_name='student_name',
        ),
        migrations.RemoveField(
            model_name='essays',
            name='content',
        ),
        migrations.AddField(
            model_name='essays',
            name='essay_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='essays',
            name='grade',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='essays',
            name='section',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
